In [1]:
import pandas as pd

In [2]:
df=pd.read_excel('cluster_0.xlsx')

In [3]:
df

,gender,age,education,city,personal_coef,product,colour,cost,product_sex,base_sale,dt,cluster
0,0,61,1,1178,0.5072,Брюки мужские Columbia Rapid Rivers Pant,серый,3439,1,1,51,0
1,0,55,1,1159,0.5072,Слипоны мужские Skechers Bounder Vertville,синий,2999,1,1,18,0
2,0,61,1,1134,0.5072,Куртка утепленная женская Northland,болотный,5849,0,1,58,0
3,0,62,1,1183,0.5072,Купальник женский FILA,темно-синий,1349,0,1,54,0
4,0,41,1,1157,0.5072,Сандалии для мальчиков Merrell Hydro Quench,черный/зеленый,3499,1,1,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...
14984,0,64,1,1188,0.5072,Ветровка женская Toread,голубой,4799,0,1,35,0
14985,0,51,1,1134,0.5072,Ветровка женская Toread,серо-голубой,5599,0,1,26,0
14986,0,37,1,1188,0.5072,Куртка утепленная для девочек Lassie Veela,розовый,2879,0,1,55,0
14987,1,42,1,1206,0.5072,Куртка для девочек Outventure,желтый,3519,0,1,7,0
14988,0,39,1,1134,0.5072,Брюки женские FILA,молочный,2999,0,1,51,0

In [4]:
df=pd.read_excel('cluster_1.xlsx')

In [5]:
df

,gender,age,education,city,personal_coef,product,colour,cost,product_sex,base_sale,dt,cluster
0,1,30,1,1188,0.4304,Замок велосипедный ABUS Catena 6806K/75,синий,4299,2,0,8,1
1,1,36,1,1134,0.4304,Бутсы мужские Demix Armando Leather TF,чёрный,5799,1,0,53,1
2,1,56,1,1152,0.4304,Ветровка мужская Demix,темно-синий,4299,1,0,23,1
3,1,46,1,1202,0.4304,Рюкзак Northland Blaze 20 л,чёрный,4699,2,0,39,1
4,1,46,1,1134,0.4304,Ботинки женские Head Ghel NBX,голубой/черный,7599,0,0,41,1
...,...,...,...,...,...,...,...,...,...,...,...,...
14249,1,49,1,1160,0.4304,Кроссовки женские GSD One,черный,1699,0,0,16,1
14250,1,41,1,1183,0.4304,Кроссовки мужские 361° Flash,оранжевый/синий/белый,8999,1,0,13,1
14251,1,61,1,1178,0.4304,Кроссовки мужские PUMA Better Foam Xterra,черный,7599,1,0,12,1
14252,1,41,1,1168,0.4304,Набор защиты Roces,черный,3999,2,0,10,1
14253,1,63,1,1147,0.4304,Полуботинки мужские Outventure Lighttrack Pro,черный,5599,1,0,6,1

In [6]:
df=pd.read_excel('cluster_2.xlsx')

In [7]:
df

,gender,age,education,city,personal_coef,product,colour,cost,product_sex,base_sale,dt,cluster
0,1,35,1,1134,0.4304,Обруч гимнастический Demix,серый,599,2,0,19,2
1,1,38,1,1162,0.4304,Футболка мужская Demix,черный,799,1,0,37,2
2,1,40,1,1199,0.4304,"Внешний аккумулятор INTERSTEP 10 000 мАч, micr...",красный,2599,2,0,35,2
3,1,31,1,1134,0.4304,Футболка мужская Demix,индиго,999,1,0,5,2
4,1,50,1,1187,0.4304,Футболка мужская Protest,светло-зеленый,899,1,0,8,2
...,...,...,...,...,...,...,...,...,...,...,...,...
15799,1,37,1,1204,0.4304,Мультиключ Cyclotech CT-10,серебряный/черный,499,2,0,4,2
15800,1,41,1,1188,0.4304,Палки треккинговые Outventure,серебряный,1799,2,0,16,2
15801,1,38,1,1188,0.4304,Крыло велосипедное заднее Stern CRM-2,черный,999,2,0,53,2
15802,1,35,1,1208,0.4304,Стельки Feet-n-Fit Cushioning Gel Support,черный,699,2,0,50,2
15803,1,45,1,1177,0.4304,Тренажер дверной для пресса Torneo,чёрный,699,2,0,9,2

In [8]:
df=pd.read_excel('cluster_3.xlsx')

In [9]:
df

,gender,age,education,city,personal_coef,product,colour,cost,product_sex,base_sale,dt,cluster
0,0,26,0,1160,0.5584,Легинсы женские FILA,фиолетовый,849,0,1,37,3
1,1,20,0,1134,0.4688,Шорты мужские Nike Dri-FIT Academy,черный/белый,2299,1,0,11,3
2,0,22,0,1174,0.5584,Брюки женские adidas,черный,2799,0,1,47,3
3,1,22,0,1192,0.4688,Куртка утепленная женская Demix,черный,5599,0,1,9,3
4,1,20,0,1134,0.4688,Кроссовки мужские Nike Air Max Alpha Trainer 4,черный/серый,11599,1,0,6,3
...,...,...,...,...,...,...,...,...,...,...,...,...
15194,1,25,0,1162,0.4688,Ботинки утепленные мужские Northland Reisen Mid,серый,5319,1,1,17,3
15195,1,19,0,1204,0.4688,Повязка FILA,черный,329,2,0,0,3
15196,0,26,0,1198,0.5584,Пластиковые велопедали Stern,черный,199,2,0,4,3
15197,1,23,0,1134,0.4688,Слипоны для девочек Skechers Beautiful Planet,сиреневый,2449,0,1,13,3
15198,1,25,0,1202,0.4688,Кеды мужские Reebok Royal Complete Sport,белый,4619,1,1,50,3

In [10]:
df=pd.read_excel('cluster_4.xlsx')

In [11]:
df

,gender,age,education,city,personal_coef,product,colour,cost,product_sex,base_sale,dt,cluster
0,0,53,1,1134,0.5072,Чехол для 1 ракетки Torneo,синий,419,2,1,18,4
1,0,41,1,1188,0.5072,Палатка 3-местная Outventure 1 Second Tent 3,темно-зелёный,8999,2,0,38,4
2,0,34,1,1134,0.5072,Шорты мужские Outventure,темно-синий,2699,1,0,8,4
3,0,40,1,1134,0.5072,Набор Outventure: стол + 4 стула,зелёный,4799,2,0,0,4
4,0,36,1,1134,0.5072,Палатка 2-местная Outventure Dome 2,темно-зелёный,4999,2,0,9,4
...,...,...,...,...,...,...,...,...,...,...,...,...
10719,1,35,1,1157,0.5072,Котел титановый Northland 0.75 л,графитовый,2999,2,0,25,4
10720,0,46,1,1192,0.5072,Сандалии детские Northland Blum,светло-розовый,3599,3,0,0,4
10721,0,35,1,1202,0.5072,"Гантель Demix, 5 кг",черный,1999,2,0,24,4
10722,0,32,1,1134,0.5072,Сумка adidas,черный,1919,2,0,56,4
10723,0,43,1,1134,0.5072,Перчатки вратарские Demix,синий,2199,2,0,18,4

In [12]:
df=pd.read_excel('cluster_5.xlsx')

In [13]:
df

,gender,age,education,city,personal_coef,product,colour,cost,product_sex,base_sale,dt,cluster
0,1,49,1,1134,0.4304,Кроссовки мужские Demix Compact 5,черный,3149,1,1,19,5
1,1,38,1,1168,0.5072,Футболка мужская Quiksilver Sunset Logo Flaxton,желтый,849,1,1,43,5
2,1,46,1,1194,0.4304,Нож Adimanti by Ganzo (Skimen design) оранжевы...,оранжевый,4699,2,1,16,5
3,1,30,1,1201,0.4304,Футболка мужская Demix,черный,599,1,1,38,5
4,1,29,1,1134,0.4304,Полуботинки мужские Outventure Discovery,черный,3219,1,1,10,5
...,...,...,...,...,...,...,...,...,...,...,...,...
14732,1,33,1,1203,0.4304,Куртка софтшелл мужская Columbia Baltic Point ...,чёрный,4999,1,1,39,5
14733,1,38,1,1191,0.4304,Кроссовки мужские Demix Bitcrazy,малахитовый,3149,1,1,35,5
14734,1,37,1,1161,0.4304,Свитшот мужской Skechers,оранжевый,2949,1,1,55,5
14735,1,55,1,1134,0.4304,Шорты плавательные мужские Joss,черный/зеленый,1259,1,1,32,5
14736,1,39,1,1188,0.4304,Кроссовки мужские 361° Flash,оранжевый/синий/белый,6299,1,1,36,5

In [14]:
df=pd.read_excel('cluster_6.xlsx')

In [15]:
df

,gender,age,education,city,personal_coef,product,colour,cost,product_sex,base_sale,dt,cluster
0,0,29,1,1188,0.5072,Сандалии женские Skechers D'Lux Walker,черный,3149,0,0,24,6
1,0,43,1,1183,0.5072,Майка для девочек Termit,розовый,699,0,0,33,6
2,0,30,1,1162,0.5072,Брюки женские Demix,черный,1749,0,0,58,6
3,0,37,1,1134,0.5072,Шорты женские Demix,черный,2299,0,0,54,6
4,0,60,1,1134,0.5072,Куртка утепленная мужская Northland,черный,5599,1,0,13,6
...,...,...,...,...,...,...,...,...,...,...,...,...
14288,0,48,1,1188,0.5072,Шорты женские Demix,черный,1299,0,0,31,6
14289,0,30,1,1156,0.5072,Сандалии женские Northland Wandern W,чёрный,3999,0,0,1,6
14290,0,32,1,1159,0.5072,Комбинезон женский укороченный EAZYWAY,серый,5590,0,0,10,6
14291,1,35,1,1188,0.5072,Свитшот женский Termit,салатовый,1999,0,0,2,6
14292,0,55,1,1179,0.5072,Полуботинки мужские Outventure Beaver,черный/зеленый,2999,1,0,16,6